name: Run Internship Scraper

on:
  schedule:
    - cron: '0 13 * * *'  # 9 AM EST
    - cron: '0 1 * * *'   # 9 PM EST
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"

      - name: Set up Python
        run: uv python install 3.14

      - name: Install Python dependencies
        run: uv sync --locked --python 3.14

      - name: Run the scraper script
        id: scraper
        env:
          MY_EMAIL_ADDRESS: ${{ secrets.MY_EMAIL_ADDRESS }}
          MY_EMAIL_APP_PASSWORD: ${{ secrets.MY_EMAIL_APP_PASSWORD }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
        run: uv run --python 3.14 main.py

      - name: Commit and push updated seen_jobs.txt
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update seen_jobs.txt with new internships"
          file_pattern: seen_jobs.txt
